services:
  frontend:
    image: "mohamedtaher26/frontend-react:latest"
    ports:
      - "8080:80"
    networks:
      - frontend_backend
    depends_on:
      - backend

  backend:
    image: "mohamedtaher26/backend-dotnet-api:latest"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: root
      DB_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - db
    networks:
      - frontend_backend
      - backend_db
    secrets:
      - db_password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend_db
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  db-data:

networks:
  frontend_backend:
  backend_db: